### ISSUE TITLE
GraphQL websocket security

### ISSUE THREAD

**Issue by alietors** [leocavalcante/siler#103]
Hi,

I am curious how we can implement authentication when subscribing on GraphQL, with the example, anyone who knows the roomName can subscribe to the websocket endpoint.

**Comment by leocavalcante** [comment]
Awesome question. GraphQL as-is does not specify any kind of authentication and/or authorization mechanisms (even something like Subscriptions, its a RFC yet), there this is delegated to client/server implementations. Apollo's client and server websocket transports layer agrees on a `connectionParams` payload over connection initialization: https://www.apollographql.com/docs/graphql-subscriptions/authentication.html Where your cliente can send a token and your server can hook a callback to intercept it.

**Comment by leocavalcante** [comment]
Since Siler lacks of something like hooks to accomplish a similar behavior, I'm will be promoting this issue to a enhancement for `v1.1`. For now the workaround would be allow a connection and restricting data thought filters and/or resolvers.

**Comment by alietors** [comment]
So, the work around will be send the token as a variable and then validate it like the roomName filter, isn't?

**Comment by leocavalcante** [comment]
Exactly, you can send user's token as a variable, like `roomName`, then authenticate and authorize it thought filters. Unfortunately, this workaround would not prevent unauthorized users to connect to your server, but allows you to at least restrict your data.

**Comment by alietors** [comment]
Awesome, thanks!
