### ISSUE TITLE
Package leocavalcante/siler at version  has a PHP requirement incompatible with your PHP version (5.6.27)

### ISSUE THREAD

**Issue by winyluo** [leocavalcante/siler#105]
Package leocavalcante/siler at version  has a PHP requirement incompatible
with your PHP version (5.6.27)

how to deal with this error?

**Comment by IvanDelsinne** [comment]
Not using php 5.6.27.

The problem here is that you're using an old and about-to-be-dead version of PHP, while siler uses a few features from PHP7.0 and PHP7.1, effectively rendering it incompatible with older versions.
