### ISSUE TITLE
Request\json crashes on empty request body

### ISSUE THREAD

**Issue by IvanDelsinne** [leocavalcante/siler#106]
If someone tries to do a `Siler\Http\Request\json()` when the request body is empty, the json_decode will fail (and return null), and the array type enforcing will fail, thus throwing a TypeError.

An example message is:

```
Fatal error: Uncaught TypeError: Return value of Siler\Http\Request\json() must be of the type array, null returned
```

**Comment by leocavalcante** [comment]
Thanks for reporting!
