### ISSUE TITLE
POST REST API

### ISSUE THREAD

**Issue by murunwas** [leocavalcante/siler#107]
How to POST json data using SILER?

**Comment by leocavalcante** [comment]
Hi @murunwas 
Actually, Siler isn't (nor provides) a HTTP client to make POST requests, for that you should consider something like [Guzzle](http://docs.guzzlephp.org/en/stable/) or [cURL](http://php.net/manual/en/book.curl.php).

On the other hand, if you what to listen for a POST request, you should use `Route\post`, than `Request\json` to extract data from it, like:

```php
Route\post('/my-post/path', function () {
    $data = Request\json();
});
```

**Comment by murunwas** [comment]
Thanks alot @leocavalcante 
soooooooooooo simple and straight forward... works like a charm

**Comment by IvanDelsinne** [comment]
You can handle File upload by using the method [`Siler\Http\Request::file`](https://github.com/leocavalcante/siler/blob/master/src/Http/Request.php#L148).

You simply use it by doing

```php
$myFile = Request\file("key");
```
