### ISSUE TITLE
Callable stops execution of router

### ISSUE THREAD

**Issue by Sinevia** [leocavalcante/siler#116]
Calling a non-static method using the default callable implementation always causes the constructors to be called, which is undesirable. See in the example below even if you call the / route, the execution will be stopped as the constructor in test will be called.

```
class TestController {
    function __construct() {
         if (has_access() == false){
             die('No Access');
         }
    }
    function page() {
        return "Page A";
    }
}
Route\get('/user', [(new TestController), "page"]);
Route\get('/', function(){
    return "Home";   
});
```

I would suggest a workaround for calling non-static methods

Route\get('/user', "TestController@page");

**Comment by leocavalcante** [comment]
Well, actually this isn't a bug. The constructor of `TestController` will always be called, indeed, you're doing it at `[(new TestController), "page"]`, it is not something on the Siler internals... We can't prevent or predict user code inside a lib/framework.

**Comment by Sinevia** [comment]
I agree it cannot be prevented, this is why I propose a workaround that will work with non-static methods without side effects

**Comment by leocavalcante** [comment]
Handling class construction isn't a Siler concern, at least for now, you should look for something like Pimple. Yet you could just wrap it in a Closure:
```php
Route\get('user', function () {
  $c = new TestController();
  return $c->page();
});
```

**Comment by Sinevia** [comment]
@leocavalcante this is actually a problem as the documentation says the router can use any callable. In this case it is a problem as it causes code execution that the user will be unaware of. I agree its not a problem with Siler per se, but this is the way this particular callable works. If Siler decides not to address this, this is fine, but the documentation needs to be updated to caveat this case.

I believe other routers have recognized this as a problem and have come up with a solution:

![image](https://user-images.githubusercontent.com/3450815/47278804-a4802280-d5c3-11e8-8346-76d21a3a1881.png)

Example at:
https://github.com/magnus-eriksson/router

**Comment by Sinevia** [comment]
@leocavalcante this is actually a problem as the documentation says the router can use any callable. In this case it is a problem as it causes code execution that the user will be unaware of. I agree its not a problem with Siler per se, but this is the way this particular callable works. If Siler decides not to address this, this is fine, but the documentation needs to be updated to caveat this case.

I believe other routers have recognized this as a problem and have come up with a solution:

![image](https://user-images.githubusercontent.com/3450815/47278804-a4802280-d5c3-11e8-8346-76d21a3a1881.png)

Example at:
https://github.com/magnus-eriksson/router

**Comment by Sinevia** [comment]
@leocavalcante this is actually a problem as the documentation says the router can use any callable. In this case it is a problem as it causes code execution that the user will be unaware of. I agree its not a problem with Siler per se, but this is the way this particular callable works. If Siler decides not to address this, this is fine, but the documentation needs to be updated to caveat this case.

I believe other routers have recognized this as a problem and have come up with a solution:

![image](https://user-images.githubusercontent.com/3450815/47278804-a4802280-d5c3-11e8-8346-76d21a3a1881.png)

Example at:
https://github.com/magnus-eriksson/router

**Comment by Sinevia** [comment]
@leocavalcante this is actually a problem as the documentation says the router can use any callable. In this case it is a problem as it causes code execution that the user will be unaware of. I agree its not a problem with Siler per se, but this is the way this particular callable works. If Siler decides not to address this, this is fine, but the documentation needs to be updated to caveat this case.

I believe other routers have recognized this as a problem and have come up with a solution:

![image](https://user-images.githubusercontent.com/3450815/47278804-a4802280-d5c3-11e8-8346-76d21a3a1881.png)

Example at:
https://github.com/magnus-eriksson/router

**Comment by leocavalcante** [comment]
NP, I got some buggy behavior from Github too.
