### ISSUE TITLE
add zendframework/zend-httphandlerrunner to emit psr-7 responce

### ISSUE THREAD

**Issue by newbie78** [leocavalcante/siler#133]
now zendframework/zend-diactoros without emit, but zendframework/zend-httphandlerrunner have it.
it will be great to add emitting psr-7 responce to framework

great job!
thanks

**Comment by newbie78** [comment]
we can use it like this:
```
use Zend\HttpHandlerRunner\Emitter\SapiEmitter;

some router code

(new SapiEmitter)->emit($response);
```

**Comment by leocavalcante** [comment]
@newbie78 
Thanks for the headsup, migration was already done, docs and examples were outdated.

**Comment by newbie78** [comment]
oh i see. sorry )
