### ISSUE TITLE
Http/path() should not replace all occurence of $scriptPath ?

### ISSUE THREAD

**Issue by yoh** [leocavalcante/siler#174]
Hi !

I think there is a problem on this line :
https://github.com/leocavalcante/siler/blob/83bf76fc00e233f86c3234f0e427484caee5ebc6/src/Http/Http.php#L113

If `$requestUri` is `/aaa` and if I have a route `/aaa/bbb/aaa/ccc`, all `aaa` portion of `$scriptPath` are replaced. I think only the first `aaa` should be replace to get `/bbb/aaa/ccc` ?

```
+        if (substr($requestUri, 0, strlen($scriptPath)) == $scriptPath) {
+            $requestUri = substr($requestUri, strlen($scriptPath));
+        }
+        return '/' . ltrim($requestUri, '/');
-        return '/' . ltrim(str_replace($scriptPath, '', $requestUri), '/');
```

**Comment by leocavalcante** [comment]
Actually, that is exactly what will happen, only the `/aaa` part will be removed, that is the real path of the script. Are you having bugs with this?

**Comment by yoh** [comment]
Yes, I have 2 times `/aaa` in my url /**aaa**/bbb/**aaa**/ccc
Only the first `/aaa` (the real part of the script) should be deleted to get `/bbb/aaa/ccc` ?

http://sandbox.onlinephpfunctions.com/code/579a3e12525423c71de444e63276d30de684fe96

**Comment by leocavalcante** [comment]
Oh, I see now. Thank you for reporting! Will you PR a fix or I can handle it?

**Comment by yoh** [comment]
Sorry for the delay... You can handle it :) 
I don't know enough Siler to know impacts of this.
