### ISSUE TITLE
Swoole Coroutine and GraphQL

### ISSUE THREAD

**Issue by johnlanz** [leocavalcante/siler#176]
How to use GraphQL with Swoole? maybe using ORM that uses mysql Coroutine or redis instead of RedBean.
Sorry for asking I just can't find any tutorial out there.

**Comment by leocavalcante** [comment]
I can work on an example project or tutorial for that. Thanks for the idea.

**Comment by ShaneJMitchell** [comment]
I also am trying to figure out how to use swoole with graphql on siler.
I am stuck with the situation that given a get request to a specified endpoint it works fine, however when doing a post request to a specified endpoint triggering `Graphql\init()` I get no response.  No error is output but no response is returned.

I have tried using calling `Swoole\json(Swoole\response(), 200);` and `return Swoole\response();` after the `Graphql\init($schema)` call (along with several other things that) but the same result.

I gave also tried calling `Graphql\execute()` as it looks like this method doesn't try to populate the response directly and it still hangs.

(any help is appreciated - the schema and resolvers were from an example that didn't require my to configure a DB connection)
my server.php file
`<?php
declare(strict_types=1);

namespace App;

$base_path = realpath(__DIR__ . '/..');
require_once $base_path . '/vendor/autoload.php';

use Siler\Monolog as Log;
use Siler\Route;
use Siler\Swoole;
use Siler\Graphql;
use Siler\Http\Request;
use Siler\Http\Response;
use Siler\Functional;
use Swoole\Runtime;

Runtime::enableCoroutine();

// Enable CORS
Response\header('Access-Control-Allow-Origin', '*');
Response\header('Access-Control-Allow-Headers', 'content-type');

try {
    Log\handler(Log\stream($base_path . '/log/http.log'));
} catch (\Exception $e) {
    echo 'Issue starting log handler - Application logging may not work: ' . $e->getMessage();
}

$handler = function ($req, $res) {
    // Log the incoming request
    Log\debug('Request', [$req]);

    try {
        // Set incoming get request parameters
        if ($get = Swoole\request()->get) {
            foreach ($get as $key => $value) {
                $_GET[$key] = $value;
            }
        }

        // set incoming post request parameters
        if ($post = Swoole\request()->post) {
            foreach ($post as $key => $value) {
                $_POST[$key] = $value;
            }
        }

        Route\get('/healthz', function () {
            Swoole\json('success');
        });

        Route\post('/', function () {
            $typeDefs = file_get_contents('../configs/schema.graphql');
            $resolvers = [
                'Query' => [
                    'message' => 'foo',
                ],
                'Mutation' => [
                    'sum' => function ($root, $args) {
                        return $args['a'] + $args['b'];
                    },
                ],
            ];

            $response = Graphql\execute(Graphql\schema($typeDefs, $resolvers), Swoole\request()->post['query']);

            if (array_key_exists('errors', $response) && $response['errors']) {
                return Swoole\json($response, 500);
            }

            return Swoole\json($response, 200);
        });

        Swoole\json('Not found', 404);
    } catch (\Exception $e) {
        // Log the exception error
        // TODO: Gracefully split output files by log level, and ensure all get piped to stream output for container use
        Log\error($e->getMessage());
        Swoole\json('An Unknown Error Has Occurred', 500);
    }
};

Swoole\http($handler)->start();
`

schema.graphql
`
type Query {
    message: String
}

type Mutation {
    sum(a: Int, b: Int): Int
}
`

**Comment by leocavalcante** [comment]
Hi folks, sorry the lack of time to work on this, but I can already advise you that you should be using `execute` instead of `init`.

**Comment by leocavalcante** [comment]
I think we have it :)
https://medium.com/@leocavalcante/build-a-graphql-api-on-top-of-swoole-5de5d71b6e12
Feel free to ask any questions!
