### ISSUE TITLE
{"errors":[{"message":"Syntax Error: Unexpected <EOF>" - UTF-8

### ISSUE THREAD

**Issue by bakuuu** [leocavalcante/siler#181]
Hi,
we have problem with graphql server based on webonyx/graphql-php and siler.
With webonyx/graphql-php everything works fine, but unfortunately, there is no subscriptions.
So, after adding siler,
after request:
'{"query":"query { myUser(id: 1) { name  }}","variables":{},"operationName":null}'
we have error:
{"errors":[{"message":"Syntax Error: Unexpected <EOF>","extensions":{"category":"graphql"},"locations":[{"line":1,"column":1}]}]}

I think it's going about - (charset=utf-8)
Content-Type: application/json; charset=utf-8

We use apollo-android library. 

the same is with request by curl or postman
When I set utf-8, I have error

how to solve it ?

**Comment by leocavalcante** [comment]
Hi,
Can you share your PHP code please or steps to reproduce the error in a minimal snippet?
Thanks.

**Comment by leocavalcante** [comment]
Please, upgrade to [v1.6.0](https://packagist.org/packages/leocavalcante/siler#v1.6.0) and check if the error persists.

**Comment by bakuuu** [comment]
It work's now. Thank You
