### ISSUE TITLE
Request\post() return empty array in PUT Method

### ISSUE THREAD

**Issue by leyume** [leocavalcante/siler#182]
Hello,
Thank you for Siler. Neat and Simple

A little issue here. 
Request\post() return empty array in PUT Method

```
# file --- foo.put.php

use Siler\Route;
use Siler\Http\Request;
use Siler\Http\Response;

$data = Request\post();
print_r($data);
```

it works for POST but doesn't work for PUT

Please can you help out here or am I doing something wrong

**Comment by leocavalcante** [comment]
Hi! Thanks for give Siler a shot.
`Request\post()` will indeed work only on `$_POST`.
For a PUT method you should use `Request\input()`
Or you can get the full input using:
- `Request\raw()` to get the full request body as string
- `Request\params()` to get the input already parsed from the URL encoded format.
- `Request\json()` to the get input already decoded from the JSON format.

**Comment by leyume** [comment]
Thank you @leocavalcante 
```Request\input()``` didn't work, BUT ```Request\params()``` Worked
