### ISSUE TITLE
Suffix for optional parameters

### ISSUE THREAD

**Issue by mnicic** [leocavalcante/siler#184]
Suffix for optional parameters is not working on my side as it is described in the documentation:
```php
Route\get('/hello/{name?}', <handler>);
```

But it's working with (mandatory `/` at the end, ex: http://localhost/hello/):
```php
Route\get('/hello/{name}?', <handler>);
```

Is it type in the doc or something else?

**Comment by leocavalcante** [comment]
Typo on the docs, thanks for the heads up!

To avoid the need of a trailing slash, add a question mark after it. It is actually pure RegExp, the `{}` thing is replaced by RegExp groups:

```php
Route\get('/hello/?{name}?', <handler>);
```

**Comment by mnicic** [comment]
Yeah, I assumed that RegEx is used here...
Thanks!
