### ISSUE TITLE
Using custom PromiseAdapter with GraphQL 

### ISSUE THREAD

**Issue by nekofar** [leocavalcante/siler#185]
I wanted to use [DataLoader](https://github.com/overblog/dataloader-php) for `GraphQL` data fetching and I needed to set it's custom `PromiseAdapter`. 

Seems like you are using `GraphQL::executeQuery` which is using builtin adapter. Is this possible for you to use `GraphQL::promiseToExecute` instead of that? Do you have any suggestion?

https://github.com/leocavalcante/siler/blob/3fe82292217701b2a8d81d70d12d56b5089a9539/src/GraphQL/GraphQL.php#L115

**Comment by leocavalcante** [comment]
There we go.
You can use `GraphQL\promise_execute()` now.

If you are using `GraphQL\init()` it only abstracts the `GraphQL\input()` and the `Response\json()` call, so you can just:

```php
<?php

use GraphQL\Executor\ExecutionResult;
use function Siler\GraphQL\{promise_execute, input};
use function Siler\Http\Response\json;

promise_execute($adapter, $schema, input())
    ->then(fn(ExecutionResult $result) => json($result->data));
```
