### ISSUE TITLE
Nested queries not executed

### ISSUE THREAD

**Issue by Jemt** [leocavalcante/siler#189]
Hi,

I need support for nested queries such as:

` init(...) { getSecretInformation { x,y,z } } `

However, none of the resolvers are invoked when using nested queries. This works though:

` init(...) getInformation { x,y,z } `

Unfortunately that is not guaranteed to be executed in the correct order on other platforms ([ref](https://graphql.github.io/graphql-spec/June2018/#sec-Normal-and-Serial-Execution)), which is what I want to achieve in this case.

I _could_ use the mutation type instead of the query type, but that just feels wrong. I'm not mutating anything, although the init(...) resolver does initialize things on the server which is needed in this case prior to the call to getInformation.

Are nested queries in fact not supported, or am I doing something wrong ?

 - Thanks in advance :-)

**Comment by leocavalcante** [comment]
Hi @Jemt 
Do you mind to make a little project to illustrate what you are trying to achieve?
I didn't get at a first glace...

**Comment by Jemt** [comment]
Hi @leocavalcante 
Thanks, I appreciate your prompt answer.
I realize that what I wrote makes no sense. I must have been really tired. Please disregard this issue.

 - Thanks again :)

**Comment by leocavalcante** [comment]
Haha, are you sure?
Maybe we can bring some cool new feature to Siler...

**Comment by Jemt** [comment]
What I wanted was support for authentication without the need to pass credentials via HTTP headers, and at the same time avoid something like passing a token with every request:
`query { persons(token:token) { name, email } }`

What I would prefer was something like the following example, but that won't work since there is no guarantee that fields are resolved in any specific order:
`query { auth(token:token) persons { name, email } }`

For some reason I - in my state of tiredness - assumed that I could nest queries like so to enforce order of execution:
`query { auth(token:token) { persons { name, email } } }` - wrong, naturally.

I could use _mutation_ instead which does guarantee order of execution, but that feels wrong.

Eventually I ended up using an Authorization header instead.

By the way, I really appreciate the work you have put in Siler GraphQL, and your example with RedBeans was exactly what I needed, so I'm now using both :-)
