### ISSUE TITLE
Combine naming and regex in route parameter

### ISSUE THREAD

**Issue by IvanDelsinne** [leocavalcante/siler#190]
Right now, we either have regex or named parameter in routes.

I think it'd be nice to have both at the same time, but that requires a change in how route parsing is handled.

**Comment by leocavalcante** [comment]
This should work already.
```php
use function Siler\Route\get;
use function Siler\Http\Response\json;

get('/{name}/([0-9]+)', function (array $params) {
    json(['name' => $params['name'], 'age' => $params[2]]);
});
```
```http
GET http://localhost:8000/leo/28
{"name":"leo","age":"28"}
```
Do you mean something else?

**Comment by IvanDelsinne** [comment]
Yes, for example, `{name:([0-9]+)}`, basically to have the ability to assign a name to a regex parameter.

**Comment by leocavalcante** [comment]
Got it.

**Comment by leocavalcante** [comment]
There we go. At regexfying it checks for matches to {name:something} then grabs 'something' and uses as the regexp of the named group.
https://github.com/leocavalcante/siler/blob/master/src/Route/Route.php#L182
