### ISSUE TITLE
Routing Issue

### ISSUE THREAD

**Issue by Zend87** [leocavalcante/siler#205]
hi @leocavalcante, I have a problem. 

I just learned your framework. 

I dont have problem when I test this :
<code>
Route\get('/', function () {
    echo 'Hello Siler';
});
</code>

But when I try this code. I got 404 page.
<code>
Route\get('/test', function () {
    echo 'Hello Siler';
});

</code>

I used apache httpd 2.4.1 and PHP 7.3.9 on my environment.

Is there an error to my code ? 
thx before & after

**Comment by leocavalcante** [comment]
Can you share more about your environment, maybe a simple example project? I got this working here...

**Comment by Zend87** [comment]
thx @leocavalcante for reply. when I edit my apache configuration 

<Directory /var/www/html>
    Options +FollowSymLinks +Multiviews
    AllowOverride All
    Order allow,deny
    Allow from all
</Directory>

the route run correctly. thx very much @leocavalcante

**Comment by leocavalcante** [comment]
Awesome \o/ keep giving Siler a try, let me know about any issues.
Cheers!
