### ISSUE TITLE
Swoole PHP Warning, http context is unavailable

### ISSUE THREAD

**Issue by leyume** [leocavalcante/siler#212]
Hello,

Still rocking the Siler and Swoole... 🚀

Got some PHP Warnings when using - Swoole\cors();

```
swoole_1    | PHP Warning:  Swoole\Http\Response::header(): http context is unavailable (maybe it has been ended or detached) in /app/vendor/leocavalcante/siler/src/Swoole/Swoole.php on line 222
swoole_1    | PHP Warning:  Swoole\Http\Response::header(): http context is unavailable (maybe it has been ended or detached) in /app/vendor/leocavalcante/siler/src/Swoole/Swoole.php on line 223
swoole_1    | PHP Warning:  Swoole\Http\Response::header(): http context is unavailable (maybe it has been ended or detached) in /app/vendor/leocavalcante/siler/src/Swoole/Swoole.php on line 224

```

Don't know if am doing something wrong or some update required in the ```/app/vendor/leocavalcante/siler/src/Swoole/Swoole.php``` file. 
Please a little help here.

Thank you

**Comment by leocavalcante** [comment]
Hi,
I guess you are using `Siler\Swoole\cors()`, right?
Can you share the piece of code where you call it or send a minimal setup to reproduce the warnings?

**Comment by leyume** [comment]
Checking through now I see the error (warning) only occurs when I run it in this manner...
I have tried to simplify as much as I can.

So I have three files mainly involved 

**index.php**
```
<?php 
declare(strict_types=1);
require_once 'vendor/autoload.php';

use Siler\Swoole;
use Siler\Route;
use Model\Redis;

$server = function () {
    new Redis();
    Route\get('/users', 'users.php');
    Swoole\emit('Not found', 404);
};

Swoole\http($server)->start();

```


**users.php**
```
<?php declare(strict_types=1);

use Siler\Swoole;

return function () {
    $users = [
        [ 'name' => 'Leo', 'author' => 'Siler' ], 
        [ 'name' => 'Salvatore', 'author' => 'Redis' ]
    ];
    Swoole\cors();
    Swoole\json($users);
};

```


**model/redis.php**

```
<?php 
namespace Model;

use Siler\Swoole;

class Redis
{
     function __construct(){
         Redis::check();
     }

    public static function check()
    {
        $path =  Swoole\request();
        Swoole\json( $path );
    }
}
```

I hope it's clear enough... Please let me know your thoughts

**Comment by leyume** [comment]
I don't mean to close the comments... that was an accident 😅

**Comment by leocavalcante** [comment]
Hm, I'm still unable to reproduce the Warning. Which version of Siler and Swoole are you using?

**Comment by leyume** [comment]
Siler - 1.6.0
Swoole - 4.4.7

**Comment by leocavalcante** [comment]
I see what is going on. You are calling `Swoole\Http\Response::header()` (through `Siler\Swoole\cors()`) after a call to `Swoole\Http\Response::end()` (through `Siler\Swoole\json()` @ `Model\Redis::check()`).

That is, you are trying to send headers to a response that was already ended/sent. Are you sure you need to emit/output something at `Model\Redis::check()`?

The key thing is that you are send some HTTP response outside a route match, so Siler tries to match the givens routes, finds `/users` and calls it with the `Swoole\cors()`.

To simple remove the warnings, you can hijack Siler telling it that a Route already has matched with `Container\set(Route\DID_MATCH, true);`:
```php
<?php

namespace Model;

use Siler\Container;
use Siler\Route;
use Siler\Swoole;

class Redis
{
    function __construct()
    {
        Redis::check();
    }

    public static function check()
    {
        $path = Swoole\request();
        Swoole\json($path);
        Container\set(Route\DID_MATCH, true);
    }
}
```

But I strongly advise you to review your architecture. `Model\Redis` would be some kind of middle-ware with fail-first capabilities? Look through it I just found out that this isn't possible yet, I can work on something like that.

**Comment by leyume** [comment]
Ok 
Thank you for your detailed response.

I will re-think and re-order the architecture... And I agree I don't need to emit here ```Model\Redis::check()``` will find a better approach

Thank you again.

**Comment by leocavalcante** [comment]
Added `Route\cancel()` to make this routing short-circuit more API friendly. You can do fancier things like:
```php
$http_handler = function () {
    if (!Redis::check(Swoole\request()) {
        Swoole\json(['error' => true, 'message' => 'Not checked']);
        Route\cancel();
    }

    // Wont be called if [Route\canceled] is true.
    Route\get('/', 'home.php');
    Route\get('/users', 'users.php');
};

```
