### ISSUE TITLE
Query string problems

### ISSUE THREAD

**Issue by josephscott** [leocavalcante/siler#214]
I was trying out Siler and noticed that query strings aren't working.  For example, `/any-route?count=1&me=2` gets converted to `/any-routecount=1&me=2` -- which doesn't match the `any-route` route, so the end result is a 404 ( no route found ).

This seems to be the problem line - https://github.com/leocavalcante/siler/blob/75b98a84d639ef3f43dbd3fd161c2d8013a56ef6/src/Http/Http.php#L107

**Comment by leocavalcante** [comment]
I have it working here:
```
GET http://localhost:8000/any-route?count=1&me=2

HTTP/1.1 200 OK
Host: localhost:8000
Date: Fri, 18 Oct 2019 13:37:27 GMT
Connection: close
X-Powered-By: PHP/7.3.10
Content-type: text/html; charset=UTF-8

Array
(
[count] => 1
[me] => 2
)


Response code: 200 (OK); Time: 319ms; Content length: 41 bytes
```
Reproduction attempt at: https://github.com/siler-examples/issue-214

Can you share more details about your code and environment, please?

**Comment by josephscott** [comment]
Using the same example code you mentioned above I run into the same problem.

Ubuntu 18.04.3 LTS using:
- PHP 7.2
- Nginx 1.14.0

The Nginx config for PHP is fairly basic, and works with other PHP code I've got running ( like WordPress and SlimPHP ):

```
location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    include fastcgi_params;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
}
```

**Comment by leocavalcante** [comment]
Hm, I still have it working with this environment.
```Dockerfile
FROM ubuntu:18.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get upgrade -y \
    && apt-get install -y nginx php-fpm

ADD nginx.conf /etc/nginx/sites-available/default

EXPOSE 80

CMD /etc/init.d/php7.2-fpm start \
    && nginx -g "daemon off;"
```
```conf
server {
    listen 80;
    server_name _;
    root /var/www/html;
    index index.php;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
    }
}
```
Can you spot any difference from yours?
https://github.com/siler-examples/issue-214/commit/5b0b7bda4acf04e81da51caedd0240335edd73ce

Maybe you are missing:
```conf
location / {
    try_files $uri /index.php$is_args$args;
}
```
To have all your routes redirected to `index.php`?

**Comment by josephscott** [comment]
I've been using:

```
    location / {
        try_files $uri $uri/ /index.php;
    }
```

**Comment by leocavalcante** [comment]
Thanks, that did it reproduce-able. The thing is that its not about Siler, if you `var_dump(_$GET)` and `var_dump($_SERVER)` you will see that `$_GET` and `$_SERVER['QUERY_STRING']` comes empty. Nginx with that instruction, Nginx isn't properly setting the query string to the CGI interface.
I will see what can be done on Siler-side.

**Comment by leocavalcante** [comment]
It really seams to be a Nginx+PHP-FPM problem.

https://serverfault.com/questions/685525/nginx-php-fpm-query-parameters-wont-be-passed-to-php
https://stackoverflow.com/questions/12654521/why-is-nginx-is-ignoring-my-query-strings
https://coderwall.com/p/rdl0kq/nginx-php-query-strings
https://kfalck.net/2011/06/19/fix-empty-nginx-fastcgi-query-strings/

**Comment by josephscott** [comment]
Not sure what is different between me and those other threads, because I get the query vars just fine:

```
var_dump( $_GET );
var_dump( $_SERVER );
```

Then call with `/?count=10&me=2` and I get variables back:

```
array(2) {
  ["count"]=>
  string(2) "10"
  ["me"]=>
  string(1) "2"
  }
```

And from `$_SERVER`:

```
["QUERY_STRING"]=>
  string(13) "count=10&me=2"
```

As noted originally, I have no problem with this setup on other PHP projects.

I can certainly adjust my config for this, but it seemed odd that it worked fine for other projects but not in Siler.
