### ISSUE TITLE
Please update composer package (debug mode)

### ISSUE THREAD

**Issue by Jemt** [leocavalcante/siler#221]
Hi,

Will the most recent version be pushed to the Composer registry anytime soon?
I manually implemented support for debugging in the GraphQL lib, but realized today that you already did this in the source code here on Github.

It is next to impossible to figure out why things are failing without support for a debug mode - at least without xdebug.

 -- Thanks in advance :-)

**Comment by leocavalcante** [comment]
Sorry about that, I'm planing a release on the end of November along side with PHP 7.4 and official PHP 7.4 support. Do you mind to use "dev-master" until? I close this issue when I update composer to remind you to switch back to a version constraint.

**Comment by Jemt** [comment]
No need to apologize. I'm thrilled with the way you made GraphQL so easy to work with. Combined with RedBeans it's just a walk in the park :-)

Please take all the time you need. I was just wondering whether the package on composer would receive regular updates, or if Github was the place to fetch new releases from here on.

Looking forward to the update once it is ready.

 - Thank you :-)

**Comment by leocavalcante** [comment]
There we go!
https://packagist.org/packages/leocavalcante/siler#1.7.0

**Comment by Jemt** [comment]
Thanks a lot! :-)
