### ISSUE TITLE
Multiple messages at GraphQL Subscriptions

### ISSUE THREAD

**Issue by Lucas286** [leocavalcante/siler#231]
Hi Leo,
I have testing your new subscription implementation. It works fine, but I noticed that when I have multiple clients subscribed, messages are multiple in each client, depending on the number of subscribed clients. If there is one client, calling the publish function causes receives one message, if there are two clients, calling the publish function receives two identical messages in each client, etc. I using Altair as a client.
Could you check if you have the same effect?

**Comment by leocavalcante** [comment]
Hi Lucas,
The subscription implementation you are using is from Swoole or Ratchet? 
If Swoole, you are using more than one worker?
Thanks!

**Comment by Lucas286** [comment]
I'm using subscriptions from Swoole, source from dev-master.
Code of subscriptions:
```
use Siler\GraphQL;
use Siler\Swoole;

require 'vendor/autoload.php';


$schema = include 'graphql/schema.php';
$filters = array();

$manager = GraphQL\subscriptions_manager($schema, $filters);
$port = 3000;

Siler\Swoole\graphql_subscriptions($manager, $port)->start();
```

schema definition:
```
type Subscription 
{
	events: String!
}
```

publish script:
```

use Siler\GraphQL;

require 'vendor/autoload.php';

GraphQL\subscriptions_at('ws://127.0.0.1:3000');

$events = 'Hello World';

GraphQL\publish('events', $events); 
```

resolver:
```
$subscriptionType = [
    'events' => function ($message) {
        // <- Received from "publish"
       return $message;
    }
];
```

**Comment by leocavalcante** [comment]
Reproducible https://github.com/siler-examples/issue-231

**Comment by Lucas286** [comment]
Great, thanks !
