### ISSUE TITLE
Route methods don't seem to work?

### ISSUE THREAD

**Issue by alturic** [leocavalcante/siler#252]
Using siler 1.7.1 on php 7.4, nginx/php-fpm.

```
use Siler\Route;
use Siler\Http\Response;

Route\get('/hello/', 'test.php');

if (!Route\did_match()) {
    Response\text('Not found', 404);
}
```

Sending GET or POST (didn't try others) to /hello/ both returned an echo that I have in test.php. Changing it to `Route\post('/hello/', 'test.php');` didn't allow a GET or POST request and kept throwing the Not found text.

Am I missing something? :(

**Comment by leocavalcante** [comment]
Hi @alturic 
I have it working:

![siler-issue252](https://user-images.githubusercontent.com/183722/73010365-1364b080-3df1-11ea-8824-88b3d6243ec8.gif)

Can you share more details about your environment or spot the differences from:
https://github.com/siler-examples/issue-252

**Comment by leocavalcante** [comment]
Did you solved it? Can I close it or help with any other questions?

**Comment by alturic** [comment]
Leo, I moved on to fastroute. You can close this issue for now.
