### ISSUE TITLE
Route\match looks like it doesn't work correctly

### ISSUE THREAD

**Issue by newbie78** [leocavalcante/siler#255]
![image](https://user-images.githubusercontent.com/28735/73740637-983cbc00-4759-11ea-9ffd-ca7f2cf6f3d4.png)

under PHP 7.3.12 commented part work perfectly, but my hoster change php ver to PHP Version 7.3.13. after that, this section was executed slowly (3 min vs 100-200 ms)

after I refactoring this part (see the picture), everything came back to normal

**Comment by newbie78** [comment]
it looks like the problem is somewhere in guzzle

**Comment by leocavalcante** [comment]
Glad you already solved it. Feel free to open or reopen any issues.
