### ISSUE TITLE
Not just annotated @EnumVal are registered as @EnumType values

### ISSUE THREAD

**Issue by francisfontoura** [leocavalcante/siler#295]
Hi!

Not annotated constants in `@EnumType` annotated classes become registered EnumType values as well. If you mix domain logic with GraphQL annotations in simpler applications, this is undesirable.

Example:
```php
/**
 * @EnumType
 */
class Status
{
    const TABLE_NAME = 'status';

    /**
     * @EnumVal
     */
    const DONE = 'done';
}
```

Expected SDL:
```graphql
enum Status {
  DONE
}
```

Generated SDL:
```graphql
enum Status {
  TABLE
  DONE
}
```

**Comment by leocavalcante** [comment]
That is a bug. Only annotated symbols should turn into GraphQL specs. Thanks for reporting.
