### ISSUE TITLE
Routing Issue if url contain Non-ASCII characters

### ISSUE THREAD

**Issue by ilcham** [leocavalcante/siler#323]
I just learned your framework. I found a problem if url contain Non-ASCII characters will return 404 ( blank ). can you help ?

Route\get('/post/{slug}?', <handler>);

жолжаксынов
victon-빅톤-mayday
আড়-ইহ-জ-র-দ-ড়-বছর-র-শ-শ-র-গল-য়-ছ-র

**Comment by leocavalcante** [comment]
Maybe just a matter of adding a multi-byte string handler to the regexp. I'll try asap.
