### ISSUE TITLE
Websocket configuration

### ISSUE THREAD

**Issue by ljfreelancer88** [leocavalcante/siler#326]
Hi, I'm checking websocket example, but I have no clue where to set configuration, example...
```
[
    // 'worker_num' => 4,
    // 'task_worker_num' => 4,
    'websocket_compression' => true,
]
```
Maybe you should add Websocket in Siler documentation including how to configure :)

`https://github.com/leocavalcante/siler/blob/master/examples/swoole-chat/server.php`

Thank you

**Comment by leocavalcante** [comment]
[The `websocket` function return is a Swoole `Server`](https://github.com/leocavalcante/siler/blob/master/src/Swoole/Swoole.php#L229), you can move it to a variable a use any Swoole settings.
```php
$server = websocket($ws_handler);
$server->set($settings);
$server->start();
```
