### ISSUE TITLE
Siler Websocket: Send messages to specific client only instead of broadcasting to all

### ISSUE THREAD

**Issue by ljfreelancer88** [leocavalcante/siler#328]
Hi, how can I send messages to specific client only instead of broadcasting the message to all? This is what I have in mind ```const ws = new WebSocket(`ws://localhost:9502?id=${from}&token=${token}`);```. Get the `id` param when sending the message but I don't the implemention in Siler.

**Comment by leocavalcante** [comment]
You can use `push()`  then pass the file descriptor as the second argument: https://github.com/leocavalcante/siler/blob/master/src/Swoole/Swoole.php#L233
