### ISSUE TITLE
Use $_ENV global instead of getenv()

### ISSUE THREAD

**Issue by leocavalcante** [leocavalcante/siler#329]
Use the `$_ENV` magic global instead of the `getenv()` function.

**Comment by trollboy** [comment]
out of curiousity why is this a bug? The only difference _should_ be case sensitivity?

**Comment by leocavalcante** [comment]
For projects that loads environments variables from files, like `symfony/dotenv` and `vlucas/phpdotenv`, it only works if populated using `putenv` which is disabled by default because it is not thread safe.
