### ISSUE TITLE
Apache virtualhost integration configuration

### ISSUE THREAD

**Issue by IvanDelsinne** [leocavalcante/siler#36]
For development, the `composer serve` script works well, but for production, it's better to run the PHP server with something like a NGINX server or an Apache server.

I looked a it in the library's source code but didn't find any clue on how to make a valid Apache2 configuration to use the `index.php` entry point file (with for example a code like below).  
Could you make an example configuration or a small documentation page ?

```php
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);

// Requiring composer deps
require_once ('./vendor/autoload.php');

use Siler\Route;
use Siler\Functional as f;

Route\get('/m', f\puts('Meow'));
Route\get('/v', f\puts('Time is '.time()));

```

**Comment by IvanDelsinne** [comment]
As I tried multiple solutions, I finally found one simple that worked.

```htaccess
RewriteEngine on
# If the file/directory exists, serving it directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# Else, rerouting the request to index.php
RewriteRule . index.php
```

**Comment by leocavalcante** [comment]
Sorry about, glad that you find a solution!
