### ISSUE TITLE
How to use Middleware and Swoole?

### ISSUE THREAD

**Issue by Lohn** [leocavalcante/siler#399]
I didn't found any examples in the documentation. There is a way to do it?

**Comment by leocavalcante** [comment]
Unfortunately there is no integration of Swoole and PSR-15, but there is a undocumented feature: https://github.com/leocavalcante/siler/blob/main/tests/Unit/Swoole/SwooleTest.php
Tests aren't clear, but it is just about using `middleware($array_of_callables)`
