### ISSUE TITLE
GraphQL annotations - nullable + listOf

### ISSUE THREAD

**Issue by gskierk** [leocavalcante/siler#430]
I created my custom input and annotated query argument that way:

```php
@GraphQL\Field(name="order", listOf=App\Inputs\OrderInput::class, nullable=true)
```
```graphql
""" This is schema fragment generated from annotations"""
type Query {
  """Get users"""
  getUsers(first: Int, offset: Int, order: [OrderInput]!): [User!]!
}
```

The result is that I cannot send request with no "order" argument and I would like to use defaults for orderBy and orderDir. Is there any solution for this problem?

**Comment by leocavalcante** [comment]
Let me check, it seams that `nullable` isn't being applied to lists, only to list elements.

**Comment by leocavalcante** [comment]
Please, try [v1.7.6](https://packagist.org/packages/leocavalcante/siler#v1.7.6) with:
```php
@GraphQL\Field(name="order", listOf=App\Inputs\OrderInput::class, nullableList=true)
```
And if you want both list and elements inside the list to be nullable, yo can combine :
```php
@GraphQL\Field(name="order", listOf=App\Inputs\OrderInput::class, nullable=true, nullableList=true)
```

**Comment by gskierk** [comment]
I can confirm that it's working! Good job 🥇
