### ISSUE TITLE
Parser in Config module

### ISSUE THREAD

**Issue by gskierk** [leocavalcante/siler#435]
I just noticed that Siler doesn't allow to specify parser in configuration module, so it's impossible to add for example [TOML](https://github.com/toml-lang/toml) support to your application. This is the source code:

```php
// \siler\src\Config\Config.php
function load($values): Config
{
    $config = new Config($values);
    Container\set(CONFIG, $config);
    return $config;
}

// \hassankhan\config\src\Config.php
public function __construct($values, ParserInterface $parser = null, $string = false)
{
    if ($string === true) {
        $this->loadFromString($values, $parser);
    } else {
        $this->loadFromFile($values, $parser);
    }
    parent::__construct($this->data);
}
```

**Comment by leocavalcante** [comment]
@gskierk I'll let this to some Hacktoberfest contributor, but tell if you need this with a certain urgency, then I can address this immediately ;)
