### ISSUE TITLE
Add a CONTRIBUTING guide

### ISSUE THREAD

**Issue by leocavalcante** [leocavalcante/siler#439]
Would be nice to have a contributing guide telling what is expected from new issues and pull requests.

**Comment by hadron43** [comment]
Hi! I'll take this. Please assign me.

**Comment by leocavalcante** [comment]
Great

**Comment by hadron43** [comment]
Any suggestions or references? Or should I do it on my own, according to my knowledge?

**Comment by leocavalcante** [comment]
It should be clear that interaction with participants must be friendly, using a non-violent communication.

And for technical considerations it must tell that some tests must be provided for new features and contributions with docs are welcome.

Also, would be nice to have some step-by-step on how to fork and start hacking into Siler :)
There are three main commands: `composer test` for unit testing, `composer analyze` for static analyses and `composer build` to run auto-generated files and the analyses+tests at once.

This infos + general contributions guidelines, like GitHub's itself guidelines in a nice written and well formatted CONTIRBUTIONS.md file, please.

**Comment by leocavalcante** [comment]
And of course, if you have more suggestion to add, it will be awesome.

**Comment by hadron43** [comment]
Sure, I'll take care of all that.

**Comment by hadron43** [comment]
My hacktoberfest id says:

> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. 

Please do this, or else this contribution won't be counted for hacktoberfest. I would be really thankful if you do it.

**Comment by leocavalcante** [comment]
Added the hacktoberfest topic.
