### ISSUE TITLE
GraphQL subscriptions cannot be setup via annotations

### ISSUE THREAD

**Issue by gskierk** [leocavalcante/siler#446]
There is no way to setup subscriptions via annotations, because deannotator doesn't look for `$deannotator->name === "Subscription"`. I'm not sure if this change would be enough, because I cannot make subscriptions work :(.

With "fixed" deannotator and the following definitions I always receive `$message = null`.

```php
<?php

namespace App;

use Siler\GraphQL\Annotation\Field;
use Siler\GraphQL\Annotation\ObjectType;
use Siler\GraphQL;

/**
 * @ObjectType(name="Query")
 */
class Query
{
    /**
     * @Field(name="hello")
     */
    public static function hello(): string
    {
        $message = 'hello world';
        GraphQL\publish('inbox', $message);

        return $message;
    }
}

//...

<?php

namespace App;

use Siler\GraphQL\Annotation\Field;
use Siler\GraphQL\Annotation\ObjectType;

/**
 * @ObjectType(name="Subscription")
 */
class Subscription
{
    /**
     * @Field(name="inbox")
     */
    public static function inbox($message): string
    {
        return $message;
    }
}
```

**Comment by leocavalcante** [comment]
Please try [v1.7.8](https://packagist.org/packages/leocavalcante/siler#v1.7.8). I've also updated the [annotations example](https://github.com/leocavalcante/siler/tree/main/examples/graphql-annotations) to use Subscriptions.

**Comment by gskierk** [comment]
@leocavalcante Yeah, it's working now, thanks! I was getting nulls, because I used GraphQL instead of GraphQL Playground.
