### ISSUE TITLE
Token processing in Config module

### ISSUE THREAD

**Issue by gskierk** [leocavalcante/siler#452]
There is no token processing feature in configuration module that is well-known from Symfony, Laminas, etc. Furthermore, I cannot find any elegant way to add it to the current implementation.

```php
$config = [
    'env' => '%env(DEBUG)%', // could be resolved to \Siler\Env\env_var('DEBUG')
];
```

I can see three potential solutions:
1. Use another dependency that supports token processing.
2. Add some workaround, it means fetch config data, process it and save it somehow again.
3. Use no dependency and develop own config. I would even leave content parsing to the user to keep it tiny and simple.

```php
function init(array $config, array $tokens);
// array<string, callable> $tokens
// $config could be easily processed with array_walk_resursive and preg_replace_callback

function get(string $path);

function set(string $key, $value);

function has(string $path);

function all();
```

@leocavalcante What do you think? Is it worth implementing? I could try to make PR with this functionality, but firstly I'd like to know your opinion.

**Comment by leocavalcante** [comment]
Hi @gskierk, good discussion here!
One thing I can already respectfully disagree is implementing something in Siler directly, I think we should wrap community implementations, it is more the Siler philosophy.

Doesn't:
```php
$config = [
    'debug' => env_bool('APP_DEBUG', false),
];
```
already works?
You just need to make sure that you load env files (if using dotenv files) before `Config\load()`.

I know it will not work in static files like ini, toml, yaml, xml etc. But it should?

**Comment by gskierk** [comment]
I meant I'd like to use it in .yaml file. It would be good to be able to store **all** configuration data in Config module, not just part of it.

Unfortunately hassankhan/config doesn't provide this functionality, but laminas/laminas-config does. So maybe is it a reasonable solution?

**Comment by leocavalcante** [comment]
Using `laminas/laminas-config` instead is good for me! It's already with another Laminas components like Diactoros and Stratagility, HttpHandlerRunner... Would you implement this?

**Comment by gskierk** [comment]
I could give it a try, please assign me to this issue :).

**Comment by leocavalcante** [comment]
Thanks!!
