### ISSUE TITLE
Paginator object with GraphQL annotations

### ISSUE THREAD

**Issue by gskierk** [leocavalcante/siler#490]
Hey, actually I'm just asking for help, but I'm sure it will be very useful to have paginator object in examples. 
@leocavalcante Have you coded it before?

- [Pagination | GraphQL](https://graphql.org/learn/pagination/)

**Comment by leocavalcante** [comment]
Never had deal with pagination before, but as far I researched, this is something solved by the implementations. I mean, at a library point-of-view we can't know what will be paged.
