### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by jordanbrauer** [leocavalcante/siler#555]
Hello! I was just curious if/when you're planning to upgrade to PHP 8? I doubt much has to change, but I tried it out and it seems that the `match` functions will need to be renamed since it is [now a language construct](https://www.php.net/manual/en/control-structures.match.php).

**Comment by leocavalcante** [comment]
Hi @jordanbrauer 
It is already [passing in the CI](https://github.com/leocavalcante/siler/runs/1779458209?check_suite_focus=true) 
The `match` issue was addressed here: https://github.com/leocavalcante/siler/commit/69e8118a8100bc2ced829a765c2d52833e3a0add

**Comment by jordanbrauer** [comment]
Awesome stuff, can't wait! Thanks again for all the great work here.
