### ISSUE TITLE
Unable to get the PUT param

### ISSUE THREAD

**Issue by manuelLandreau** [leocavalcante/siler#66]
Hi, either in Siler\Request or Siler\Diactoros it is possible to get the URI param (using Route\resource), I just tried THE PUT verb :  PUT | /users/{id} | update.php
Anyway i did that : 

`$id = explode('/', \Siler\Diactoros\request()->getServerParams()['REQUEST_URI'])[2];`

Is there an other possibility ?
Thanx, Great work by the way.

EDIT: 
I just figured out : 
I put $id = array_get($params, 'id') in any controller and it works, i don't where this "global variable" come from but it works.

**Comment by leocavalcante** [comment]
Hi @manuelLandreau 
Glad that you figured it out.
The `$params` variables comes from the router resolution, then its passed as an parameter for the whatever callback is given:
https://github.com/leocavalcante/siler/blob/master/src/Route/Route.php#L87
