### ISSUE TITLE
Fresh Install getting error 

### ISSUE THREAD

**Issue by aalasolutions** [leocavalcante/siler#79]
I have installed this in a subfolder and I am getting this error

    Parse error: syntax error, unexpected '(' in /Users/XYZ/Work/htdocs/project/vendor/leocavalcante/siler/src/Functional/Functional.php on line 113

This error comes when I access site like http://localhost/project/

But when I do `composer serve` site works fine over http://localhost:8000/

I have to put this on a shared hosting where I can not run composer serve

**Comment by aalasolutions** [comment]
Hmm okay, I guess issue is with Older version of PHP, I have php 5.5 (guess) in xampp and when I run php from CLI mac runs 7+ version, causing this issue.

**Comment by leocavalcante** [comment]
Hi @aalasolutions 
Sorry, but Siler is 7.1 >=
https://en.wikipedia.org/wiki/PHP#Release_history
Current version and -1 philosophy.
Most hosting systems has already upgraded to at least 7.0, so...

**Comment by aalasolutions** [comment]
Yeah I understand, 👍
