### ISSUE TITLE
GraphQL example

### ISSUE THREAD

**Issue by buksy90** [leocavalcante/siler#80]
Hello,

I have followed graphQL example from docs https://siler.leocavalcante.com/graphql/ but it doesnt work to me. When I run GraphiQl  with:

```
query {
  rooms {
    id
    name
  }
}
```

I get following result:

```
{
  "errors": [
    {
      "message": "Syntax Error GraphQL (1:1) Unexpected <EOF>\n\n1: \n   ^\n",
      "category": "graphql",
      "locations": [
        {
          "line": 1,
          "column": 1
        }
      ]
    }
  ]
}
```

I have installed all the dependencies (composer.json).

```
{
  "require": {
    "leocavalcante/siler": "dev-master",
    "webonyx/graphql-php": "^0.11.5",
    "gabordemooij/redbean": "^5.0"
  }
}
```

There isnt any error in apache/error log.  What could be causing the problem?

**Comment by leocavalcante** [comment]
Hi @buksy90 

Just did a successful installation from scratch following the guide.
![image](https://user-images.githubusercontent.com/183722/34907355-7c2eeec0-f864-11e7-9069-057d1fb49bb4.png)

What GraphiQL app are you using to test? By the error, the query wasn't recognized from the request. Siler will handle `x-www-form-urlencoded` and `json`, are you using a different Content-type?

**Comment by buksy90** [comment]
Hello,

Im using ChromeiQL v.1.0 and it looks like the extension sends request with header "Content-Type:application/json". Since you were able to create successful installation, I tried again and got same error. Here's git repository of the test https://github.com/buksy90/grapql_test 

Could you please take a look? Im running php 7.0.22.

Thank you in advance :).

**Comment by leocavalcante** [comment]
@buksy90 
I get the error only on the first load because of the initial commit message. But queries are working fine:

![image](https://user-images.githubusercontent.com/183722/34950642-e4748a3e-f9fa-11e7-95e8-e0e028fed6e6.png)

^ running a clone of you project without any modifications, just a `composer install`.

**Comment by cintarembo** [comment]
When i try with 
`php -S localhost:8000/graphql/api.php` it's works fine 

but when i tried use 
XAMPP or apache built in OSX

i get same result as @buksy90 

![jepretan layar 2018-01-26 pada 18 16 19](https://user-images.githubusercontent.com/24893399/35437460-1125f0cc-02c5-11e8-9f9d-2549775a3950.png)

**Comment by buksy90** [comment]
It will be probably something with our apache/php settings. Where does the library read input from ($_GET/$_POST/php://input) ?

**Comment by cintarembo** [comment]
@buksy90 library read input from php://input . 
You can see in `vendor/leocavalcante/src/Graphql/Graphql.php` on the init function 

CMIIW

**Comment by leocavalcante** [comment]
Sorry about that folks.
I was able to reproduce using the php:apache Docker image.
It was about fetching Content-Type from headers as mentioned by @cintarembo on the edit.
Can you refetch dev-master with `composer update` to check if its working now?

I tested the example running on [php:apache](https://hub.docker.com/_/php/) and GraphQL Playground.

Cheers.

**Comment by buksy90** [comment]
Great man, it works now :).

Thanks
