### ISSUE TITLE
when can we expect a release?

### ISSUE THREAD

**Issue by newbie78** [leocavalcante/siler#81]
I like your project and approach to design.
when can we expect a release?
it would be good to introduce boilrplate to framework's recommended directory structure (like lumen or so)..

**Comment by leocavalcante** [comment]
Hi @newbie78 
I think we need more proof of work, I get some feedback by e-mail from people using Siler, but isn't enough to consider it battle-tested.
If you think it is worthy to use Siler in you next project, please do and feel free to ask for help and support here in the issues.
Cheers.

**Comment by leocavalcante** [comment]
Just remembered. @manuelLandreau did some nice work at: https://github.com/manuelLandreau/siler-product

**Comment by newbie78** [comment]
thanks for the reply!

good work done @manuelLandreau, but I see in the dependencies json illuminate/support package. that's not good (http://mattallan.org/2016/dont-use-illuminate-support/). now I am trying to transfer one of my pet projects to siler.
I will try to share the results after that.

**Comment by leocavalcante** [comment]
Awesome, thanks. Looking forward to see your thoughts on Siler.

**Comment by leocavalcante** [comment]
Here we go!
