### ISSUE TITLE
Adding a resolveType

### ISSUE THREAD

**Issue by factormaarten** [leocavalcante/siler#835]
In Webonyx you can add a resolve type as seen in: https://webonyx.github.io/graphql-php/type-definitions/unions/
I'm currently resolving my query in this way:

```php
'events' => function ($message) {
   return $message;
}
```

How can I add a resolve type?

My graphql is like this:
```
union EventTypes = UserEvent | TradeEvent

type Event {
    type: String
    payload: UserEvent
}

type UserEvent {
    user: User
}

type TradeEvent {
    trade: Trade
}
```

**Comment by leocavalcante** [comment]
When you use `Siler\GraphQL\schema()`, the second argument is an array of resolvers where the key is the type.
