### ISSUE TITLE
Make siler more tiny

### ISSUE THREAD

**Issue by eghojansu** [leocavalcante/siler#88]
We can split siler plugins into its own repository. I know it's sound silly to make repo for tiny source code, but it will make dependency more implicit.
As example, if we require twig functionality, we simply require `siler/twig` and composer will do the job to install `twig/twig` too.

**Comment by leocavalcante** [comment]
Yeah, I thought about that. It should be something from the beginning. For now, I think we could keep them together, isn't that much, not a big deal.

**Comment by eghojansu** [comment]
Cool, i am creating a sample blog using siler. I'll inform when done, may be this afternoon

**Comment by leocavalcante** [comment]
Awesome, I'd love to have some feedback about Siler on production-grade projects.
