### ISSUE TITLE
How to implement Interface and Union 

### ISSUE THREAD

**Issue by razorback21** [leocavalcante/siler#886]
Hi, I have this schema below. I am wondering how to create a type resolver. 

interface Item {
   price: Int
   code: String
}

type Tile implements Item {
   price: Int
   code: String
   size: String
}

type RegularProduct implements Item {
   price: Int
   code: String
   weight: String
} 

union = Tile | RegularProduct

**Comment by razorback21** [comment]
Thanks. I havent seen there is another way of creating object types. Is it.possible to use both annotation and the simpler one? or merge both?. I have already written alot of types in schema.graphql and it will take alot of work to convert each type to classes. 

Sent from Yahoo Mail on Android 
 
  On Fri, 11 Feb 2022 at 7:42 pm, Leo ***@***.***> wrote:   


Hi,
You can use @UnionType annotation then specify the types at the types array like: https://github.com/leocavalcante/siler/blob/main/examples/graphql-annotations/src/FooBar.php#L8

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leocavalcante** [comment]
Alright, got it. Have you tried to assign a `callable` to the union type like any regular type already?
Something like:

```graphql
type Foo {}
type Bar {}
union FooBar = Foo | Bar
```

```php
$fooType = function () {};
$barType = function () {};
$fooBarType = function () {};

$resolvers = [
    'Foo' => $fooType,
    'Bar' => $barType,
    'FooBar' => $fooBarType,
    'Query' => $queryType,
    'Mutation' => $mutationType,
];
```

**Comment by razorback21** [comment]
Yes. I have pretty much the same code except I have no idea what code to create inside $fooBarType = function () {}. Sorry. Can you share a code sample? 

Below is my resolver code.

$fooType = function () {
   return [
     'size' => function($root) {
          return  $root['size'];
      }
]
};
$barType = function () {
    return [
     'weight' => function($root) {
          return  $root['weight'];
      }
};

$fooBarType = function () {
     // I can't figure out how to resolve fooType & barType in here
};

$resolvers = [
    'Foo' => $fooType,
    'Bar' => $barType,
    'FooBar' => $fooBarType,
    'Query' => $queryType,
];

**Comment by leocavalcante** [comment]
I'd usually implement an Union in GraphQL as an Abstract Class in PHP that both types implements.
```php
abstract class FooBar {}
final class Foo extends FooBar {}
final class Bar extends FooBar {}
```
There you can have thing that are to both classes. Maybe that it the place for your `Item`.
```php
abstract class Item {}
final class Tile extends Item {}
final class RegularProduct extends Item {}
```

**Comment by leocavalcante** [comment]
I'm afraid that it is currently not possible.

**Comment by razorback21** [comment]
Thanks for the help. I will just convert my code to annotated version.
