### ISSUE TITLE
GraphQL Annotation for Types Arguments

### ISSUE THREAD

**Issue by razorback21** [leocavalcante/siler#887]
Hi, My Query type looks like this `Login (Email: String!, Password: String!): LoginResponse`. I can't find the documentation or samples on how to convert that into annotated version. Help would be much appreciated.

**Comment by leocavalcante** [comment]
It would be something like:
```php
/**
 * @ObjectType()
 */
class LoginResponse
{
}

/**
 * @ObjectType()
 */
class Query
{
    /**
     * @Field(description="Authenticate the user")
     * @Args({
     *     @Field(name="Email", type="string"),
     *     @Field(name="Password", type="string")
     * })
     */
    public function Login($root, array $args): LoginResponse
    {
        $args['Email'];
        $args['Password'];

        return new LoginResponse();
    }
}

**Comment by razorback21** [comment]
How do you pass an array of Int types in an annotation? 

`@Field(name="ID", type="[Int]", nullable=true), // doesnt work`

**Comment by razorback21** [comment]
I have figure it out `@Field(name="IDs", type="Int", listOf="Int", nullable=true),`
