### ISSUE TITLE
Typo on method doc for recommended_locale

### ISSUE THREAD

**Issue by IvanDelsinne** [leocavalcante/siler#94]
The line [239](https://github.com/leocavalcante/siler/blob/master/src/Http/Request.php#L239) have `$_SESSION['lang]` where it should be `$_SESSION['lang']`.

I'd like to avoid opening a PR just for that, could you correct that typo ?

Also, switching `''` with `""` line [248](https://github.com/leocavalcante/siler/blob/master/src/Http/Request.php#L248), so Github syntax coloration is happy !

**Comment by leocavalcante** [comment]
There is it.
