### ISSUE TITLE
Support graphql-ws protocol

### ISSUE THREAD

**Issue by mitjarobic** [leocavalcante/siler#96]
Refactoring needed for subscriptions

**Comment by leocavalcante** [comment]
@mitjarobic 
build is failing because of the static analysis that I'll be fixing right now, but new GraphQL over WebSocket protocol is ready and tests passing.

**Comment by mitjarobic** [comment]
@leocavalcante  Great! Thank you. Did you test it via graphiql? Can you maybe also update this repo so i can get a working example?

https://github.com/leocavalcante/graphiql-app

**Comment by leocavalcante** [comment]
Hi @mitjarobic 
I tested it over https://github.com/apollographql/apollo-server using `graphiqlExpress`

**Comment by mitjarobic** [comment]
@leocavalcante It works:) Thank you :)
